version: '3.9'
services:
  web:
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    image: authentication:1.0.0
    container_name: authentication
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    env_file:
      - .env
    ports:
      - "8001:8001"
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    # command: sh -c "chmod +x /app/migrate.sh && chmod +x /app/entrypoint.sh"
    # volumes:
    #   - staticfiles:/app/staticfiles/
  
  postgres_db:
    image: postgres:latest
    restart: always
    command: -p 5434
    env_file:
      - .env
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  redis_db:
    image: redis:latest
    restart: always
    expose:
      - 6380
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6380

volumes:
  postgres_data:
  redis_data:
