version: '3.9'

services:
  web:
    container_name: authentication
    image: authentication:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    env_file:
      - .env
    ports:
      - "8001:8000"
    # command: sh -c "chmod +x /app/migrate.sh && chmod +x /app/entrypoint.sh && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - staticfiles:/app/staticfiles
    depends_on:
      - db  

  db:
    image: postgres:latest
    restart: always
    command: -p 5434
    env_file:
      - .env
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    expose:
      - 6380
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6380

volumes:
  postgres_data:  
  redis_data:    
  staticfiles:  
